FROM ruby:2.6.5

RUN apt-get update -qq && apt-get install -y postgresql-client graphviz

# for a JS runtime
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# for a yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update -qq && apt-get install -y yarn

#COPY bin/setup_chrome ./
# Install Chrome WebDriver
#RUN CHROMEDRIVER_VERSION='86.0.4240.22' ./setup_chrome

# Add a script to be executed every time the container starts.
COPY docker/docker-entrypoint /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint

RUN mkdir /app
WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

RUN bundle install
RUN yarn install

COPY . /app
